add_lunch_combo crom_galaxysmtd-userdebug
add_lunch_combo crom_hlte-userdebug
add_lunch_combo crom_i9100-userdebug
add_lunch_combo crom_jflte-userdebug
add_lunch_combo crom_mako-userdebug
add_lunch_combo crom_m7-userdebug
add_lunch_combo crom_hammerhead-userdebug
